name: Linode Cleanup

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: "0 */8 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Linode CLI
        run: |
          pipx install linode-cli

      - name: Cleanup
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_CLI_TOKEN }}
        run: |
          ./hack/scripts/linode-cleanup.sh
          ./hack/scripts/linode-cleanup.sh
          ./hack/scripts/linode-cleanup.sh
